<h1 style="text-align:center; color:cyan; font-size:40px;">
    STOCK MARKET ANALYZER
</h1>

## 📌 Introduction

This project performs a comprehensive analysis of stock market data using only NumPy, without relying on additional libraries.

---

## 📊 Dataset Description

The dataset consists of stock prices for multiple stocks over several days.

- **Rows** represent different stocks  
- **Columns** represent daily prices  

### Example:
- Stock A → prices over 5 days  
- Stock B → prices over 5 days  
- Stock C → prices over 5 days  

In [10]:
import numpy as np

In [11]:
stocks = np.array(["A", "B", "C"])

prices = np.array([
    [100, 102, 101, 105, 110],   
    [200, 198, 202, 205, 207],  
    [50, 55, 53, 52, 58]         
])

print("Stock Prices:\n", prices)

Stock Prices:
 [[100 102 101 105 110]
 [200 198 202 205 207]
 [ 50  55  53  52  58]]


In [12]:
daily_returns = (prices[:, 1:] - prices[:, :-1]) / prices[:, :-1] * 100

print("📊 Daily Returns (%):\n", daily_returns)

📊 Daily Returns (%):
 [[ 2.         -0.98039216  3.96039604  4.76190476]
 [-1.          2.02020202  1.48514851  0.97560976]
 [10.         -3.63636364 -1.88679245 11.53846154]]


In [13]:
avg_return = np.mean(daily_returns, axis=1)

for i in range(len(stocks)):
    print(f"Average Return of Stock {stocks[i]}: {avg_return[i]:.2f}%")

Average Return of Stock A: 2.44%
Average Return of Stock B: 0.87%
Average Return of Stock C: 4.00%


In [28]:
volatility = np.std(daily_returns, axis=1)

for i in range(len(stocks)):
    print(f"Volatility of Stock {stocks[i]}: {volatility[i]:.2f}")

Volatility of Stock A: 2.21
Volatility of Stock B: 1.14
Volatility of Stock C: 6.82


In [15]:
total_growth = ((prices[:, -1] - prices[:, 0]) / prices[:, 0]) * 100

best_stock = np.argmax(total_growth)
worst_stock = np.argmin(total_growth)

print(f"🚀 Best Stock: {stocks[best_stock]} ({total_growth[best_stock]:.2f}%)")
print(f"⚠️ Worst Stock: {stocks[worst_stock]} ({total_growth[worst_stock]:.2f}%)")

🚀 Best Stock: C (16.00%)
⚠️ Worst Stock: B (3.50%)


In [16]:
max_gain = np.max(daily_returns)
index = np.unravel_index(np.argmax(daily_returns), daily_returns.shape)

print(f"📈 Highest Gain: {max_gain:.2f}%")
print(f"Stock: {stocks[index[0]]}, Day: {index[1] + 1}")

📈 Highest Gain: 11.54%
Stock: C, Day: 4


In [17]:
window = 3

moving_avg = np.array([
    np.convolve(stock, np.ones(window)/window, mode='valid')
    for stock in prices
])

print("📊 Moving Averages:\n", moving_avg)

📊 Moving Averages:
 [[101.         102.66666667 105.33333333]
 [200.         201.66666667 204.66666667]
 [ 52.66666667  53.33333333  54.33333333]]


In [18]:
cumulative_returns = (prices / prices[:, [0]]) - 1

print("📈 Cumulative Returns:\n", cumulative_returns)

📈 Cumulative Returns:
 [[ 0.     0.02   0.01   0.05   0.1  ]
 [ 0.    -0.01   0.01   0.025  0.035]
 [ 0.     0.1    0.06   0.04   0.16 ]]


In [19]:
portfolio = np.mean(prices, axis=0)

portfolio_return = ((portfolio[-1] - portfolio[0]) / portfolio[0]) * 100

print(f"💼 Portfolio Return: {portfolio_return:.2f}%")

💼 Portfolio Return: 7.14%


In [20]:
predicted_next = np.mean(prices[:, -3:], axis=1)

for i in range(len(stocks)):
    print(f"🔮 Predicted Next Price of {stocks[i]}: {predicted_next[i]:.2f}")

🔮 Predicted Next Price of A: 105.33
🔮 Predicted Next Price of B: 204.67
🔮 Predicted Next Price of C: 54.33


In [21]:
print("📊 Risk vs Return:")

for i in range(len(stocks)):
    print(f"Stock {stocks[i]} → Return: {avg_return[i]:.2f}% | Risk: {volatility[i]:.2f}")

📊 Risk vs Return:
Stock A → Return: 2.44% | Risk: 2.21
Stock B → Return: 0.87% | Risk: 1.14
Stock C → Return: 4.00% | Risk: 6.82


In [22]:
correlation_matrix = np.corrcoef(prices)

print("📊 Correlation Matrix:\n", correlation_matrix)

📊 Correlation Matrix:
 [[1.         0.84557032 0.7756541 ]
 [0.84557032 1.         0.42260104]
 [0.7756541  0.42260104 1.        ]]


In [27]:
risk_free_rate = 1  

sharpe_ratio = (avg_return - risk_free_rate) / volatility

print("📈 Sharpe Ratio:")

for i in range(len(stocks)):
    print(f"Stock {stocks[i]}: {sharpe_ratio[i]:.2f}")

📈 Sharpe Ratio:
Stock A: 0.65
Stock B: -0.11
Stock C: 0.44


In [24]:
drawdown = []

for stock in prices:
    peak = np.maximum.accumulate(stock)
    dd = (stock - peak) / peak
    drawdown.append(np.min(dd))

drawdown = np.array(drawdown)

print("📉 Maximum Drawdown:")

for i in range(len(stocks)):
    print(f"Stock {stocks[i]}: {drawdown[i]:.2f}")

📉 Maximum Drawdown:
Stock A: -0.01
Stock B: -0.01
Stock C: -0.05


In [25]:
mean_price = np.mean(prices, axis=1, keepdims=True)
std_price = np.std(prices, axis=1, keepdims=True)

z_scores = (prices - mean_price) / std_price

print("⚠️ Z-Scores:\n", z_scores)

⚠️ Z-Scores:
 [[-0.9969278  -0.44307902 -0.72000341  0.38769414  1.77231608]
 [-0.73576721 -1.34890655 -0.12262787  0.79708114  1.41022048]
 [-1.31982404  0.5132649  -0.21997067 -0.58658846  1.61311827]]


In [26]:
weights = np.array([0.5, 0.3, 0.2])

portfolio_weighted = np.dot(weights, prices)

portfolio_return = ((portfolio_weighted[-1] - portfolio_weighted[0]) / portfolio_weighted[0]) * 100

print(f"💼 Weighted Portfolio Return: {portfolio_return:.2f}%")

💼 Weighted Portfolio Return: 7.25%
